name: build_and_push_to_ecr

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - finalize-app-and-action

permissions:
  id-token: write
  contents: write

jobs:
  build_and_push_to_ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::920373021859:role/ze_my_admin_role
          aws-region: eu-west-1
          role-session-name: APIActions
          role-duration-seconds: 3600

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up yq
        run: |
          sudo apt-get update > /dev/null 2>&1
          sudo apt-get install -y wget > /dev/null 2>&1
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Build & push
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI="${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/ze_my_ecr"
          docker build -t $ECR_URI:$GITHUB_SHA .
          docker tag $ECR_URI:$GITHUB_SHA $ECR_URI:latest
          docker push $ECR_URI:$GITHUB_SHA
          docker push $ECR_URI:latest

      - name: Verify Docker image in ECR
        run: |
          aws ecr describe-images --repository-name ze_my_ecr --region eu-west-1

      - name: Set up Git
        run: |
          git config --global user.name '{{ secrets.USER_NAME }}'
          git config --global user.email '{{ secrets.USER_EMAIL }}'
  
      - name: Clone target repository
        run: |
          git clone https://${{ secrets.PAT_ACTIONS }}@github.com/edgaroviz/devops-infra.git

      - name: Append image tag in kustomize deployment
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_ACTIONS }}
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI="${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/ze_my_ecr"
          echo "Hash ${{ github.sha }} is updated as image tag in values file"
          yq eval ".spec.template.spec.containers[0].image = \"${ECR_URI}:${{ github.sha }}\"" -i devops-infra/kustomize-base/deployment.yaml
          git -C devops-infra add kustomize-base/deployment.yaml
          git -C devops-infra commit -m "Updated image tag to ${{ github.sha }}"
          git -C devops-infra push origin master
          echo "Hash ${{ github.sha }} is pushed to values file image tag" >> $GITHUB_STEP_SUMMARY
