name: build_and_push_to_ecr

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_push_to_ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & push
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          
          ECR_URI="${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/ze-my-ecr"
          
          cd counter_service
          docker build -t $ECR_URI:$GITHUB_SHA .

          docker tag $ECR_URI:$GITHUB_SHA $ECR_URI:latest

          docker push $ECR_URI:$GITHUB_SHA
          docker push $ECR_URI:latest

      - name: Verify Docker image in ECR
        run: |
          aws ecr describe-images --repository-name ze-my-ecr --region eu-west-1